# fly.toml file generated for reactivities-peng on 2023-03-30T12:54:15+01:00

app = "reactivities-peng"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ams"
processes = []

[build]
  image = "zeepad/reactivities:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Cloudinary__CloudName= "dlie6bs1j"
  Cloudinary__ApiKey= "362663824488835"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
